<?php

namespace Database\Seeders;

use App\Models\CreditTransaction;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CreditTransactionSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::pluck('urn')->toArray(); // Get all user URNs

        if (empty($users)) {
            $this->command->info('No users found. Seed some users first.');
            return;
        }

        // Seed 50 transactions for last week
        for ($i = 0; $i < 25; $i++) {
            $this->createTransaction($users, Carbon::now()->subDays(rand(7, 13)), $i + 1);
        }

        // Seed 50 transactions for this week
        for ($i = 0; $i < 25; $i++) {
            $this->createTransaction($users, Carbon::now()->subDays(rand(0, 6)), $i + 26);
        }

        $this->command->info('50 credit transactions seeded for last week and 50 for this week!');
    }

    private function createTransaction(array $users, Carbon $date, int $sortOrder): void
    {
        $senderUrn = $users[array_rand($users)];
        $receiverUrn = $users[array_rand($users)];

        // Avoid sender = receiver
        while ($receiverUrn === $senderUrn) {
            $receiverUrn = $users[array_rand($users)];
        }

        CreditTransaction::create([
            'sort_order' => $sortOrder,
            'sender_urn' => $senderUrn,
            'receiver_urn' => $receiverUrn,
            'calculation_type' => rand(0, 1), // 0 = Debit, 1 = Credit
            'source_id' => rand(1, 10),
            'source_type' => 'App\\Models\\SomeSource',
            'transaction_type' => rand(0, 6),
            'status' => rand(0, 4),
            'amount' => rand(10, 5000),
            'credits' => rand(1, 100),
            'description' => 'Dummy transaction #' . $sortOrder,
            'metadata' => [
                'note' => 'Generated by seeder',
            ],
            'creater_id' => 1,
            'updater_id' => 1,
            'creater_type' => 'Seeder',
            'updater_type' => 'Seeder',
            'created_at' => $date,
            'updated_at' => $date,
        ]);
    }
}
